### ISSUE TITLE
Chocolate and honey render as usual water

### ISSUE THREAD

**Issue by Defetyre** [alula/Create-1.19.2#2]
### Describe the Bug
Sodium is present. This does not happen to liquid from other mods. Switching off shaders and flywheel engine changes nothing.

### Expected Result

Chocolate and honey render as chocolate and honey

### Screenshots and Videos

![2022-10-09_00 33 47](https://user-images.githubusercontent.com/88449275/194720439-4c8ebf4c-70c9-40f1-b6a1-38705e7f0f66.png) On the right is liquid from another mod for a reference

### Minecraft Version

1.19.2

**Comment by Sheep7798** [comment]
It’s related to registrate not having fluid attributes rn
